[package]
name = "dolores"
version = "0.1.0"
edition = "2021"

authors = ["Rami3L <rami3l@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.48"
clap = "3.0.0-beta.5"
itertools = "0.10.1"
logos = "0.12.0"
nom = "7.1.0"
rustyline = "9.0.0"

[dev-dependencies]
assert_matches = "1.5.0"
indoc = "1.0.3"
pretty_assertions = "1.0.0"
